// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.8
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_codegen.cpp:451

#ifndef _TAO_IDL_TAOOUTPOUT_MESSENGERTYPESUPPORTSERVER_QDWVXB_H_
#define _TAO_IDL_TAOOUTPOUT_MESSENGERTYPESUPPORTSERVER_QDWVXB_H_

#include /**/ "ace/pre.h"

#include "MessengerTypeSupportClient.hpp"
#include "MessengerServer.hpp"
#include "dds/DdsDcpsInfrastructureServer.hpp"
#include "dds/DdsDcpsPublicationServer.hpp"
#include "dds/DdsDcpsSubscriptionExtServer.hpp"
#include "dds/DdsDcpsTopicServer.hpp"
#include "dds/DdsDcpsTypeSupportExtServer.hpp"
#include <tao/PortableServer/Basic_SArguments.h>
#include <tao/PortableServer/Special_Basic_SArguments.h>
#include <tao/PortableServer/Fixed_Size_SArgument_T.h>
#include <tao/PortableServer/Var_Size_SArgument_T.h>

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:35

namespace POA_cfs
{
  

  // TAO_IDL - Generated from
  // /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:35

  namespace com
  {
    

    // TAO_IDL - Generated from
    // /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:35

    namespace Messenger
    {
      
    
    // TAO_IDL - Generated from
    // /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:66

    } // module cfs::com::Messenger
  
  // TAO_IDL - Generated from
  // /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:66

  } // module cfs::com

// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:66

} // module cfs

#include /**/ "ace/post.h"

#endif /* ifndef */

