// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.8
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_codegen.cpp:366


#include "MessengerTypeSupportClient.hpp"
#include <tao/CDR.h>
#include <ace/OS_NS_string.h>

#if !defined (__ACE_INLINE__)
#include "MessengerTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for cfs::com::Messenger::MessageTypeSupport.

cfs::com::Messenger::MessageTypeSupport_ptr
TAO::Objref_Traits<cfs::com::Messenger::MessageTypeSupport>::duplicate (
    cfs::com::Messenger::MessageTypeSupport_ptr p)
{
  return cfs::com::Messenger::MessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<cfs::com::Messenger::MessageTypeSupport>::release (
    cfs::com::Messenger::MessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

cfs::com::Messenger::MessageTypeSupport_ptr
TAO::Objref_Traits<cfs::com::Messenger::MessageTypeSupport>::nil (void)
{
  return cfs::com::Messenger::MessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<cfs::com::Messenger::MessageTypeSupport>::marshal (
    const cfs::com::Messenger::MessageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



cfs::com::Messenger::MessageTypeSupport::MessageTypeSupport (void)
{}

cfs::com::Messenger::MessageTypeSupport::~MessageTypeSupport (void)
{
}

cfs::com::Messenger::MessageTypeSupport_ptr
cfs::com::Messenger::MessageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

cfs::com::Messenger::MessageTypeSupport_ptr
cfs::com::Messenger::MessageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

cfs::com::Messenger::MessageTypeSupport_ptr
cfs::com::Messenger::MessageTypeSupport::_nil (void)
{
  return 0;
}

cfs::com::Messenger::MessageTypeSupport_ptr
cfs::com::Messenger::MessageTypeSupport::_duplicate (MessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
cfs::com::Messenger::MessageTypeSupport::_tao_release (MessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
cfs::com::Messenger::MessageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:cfs/com/Messenger/MessageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* cfs::com::Messenger::MessageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:cfs/com/Messenger/MessageTypeSupport:1.0";
}

::CORBA::Boolean
cfs::com::Messenger::MessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for cfs::com::Messenger::MessageDataWriter.

cfs::com::Messenger::MessageDataWriter_ptr
TAO::Objref_Traits<cfs::com::Messenger::MessageDataWriter>::duplicate (
    cfs::com::Messenger::MessageDataWriter_ptr p)
{
  return cfs::com::Messenger::MessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<cfs::com::Messenger::MessageDataWriter>::release (
    cfs::com::Messenger::MessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

cfs::com::Messenger::MessageDataWriter_ptr
TAO::Objref_Traits<cfs::com::Messenger::MessageDataWriter>::nil (void)
{
  return cfs::com::Messenger::MessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<cfs::com::Messenger::MessageDataWriter>::marshal (
    const cfs::com::Messenger::MessageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



cfs::com::Messenger::MessageDataWriter::MessageDataWriter (void)
{}

cfs::com::Messenger::MessageDataWriter::~MessageDataWriter (void)
{
}

cfs::com::Messenger::MessageDataWriter_ptr
cfs::com::Messenger::MessageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

cfs::com::Messenger::MessageDataWriter_ptr
cfs::com::Messenger::MessageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

cfs::com::Messenger::MessageDataWriter_ptr
cfs::com::Messenger::MessageDataWriter::_nil (void)
{
  return 0;
}

cfs::com::Messenger::MessageDataWriter_ptr
cfs::com::Messenger::MessageDataWriter::_duplicate (MessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
cfs::com::Messenger::MessageDataWriter::_tao_release (MessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
cfs::com::Messenger::MessageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:cfs/com/Messenger/MessageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* cfs::com::Messenger::MessageDataWriter::_interface_repository_id (void) const
{
  return "IDL:cfs/com/Messenger/MessageDataWriter:1.0";
}

::CORBA::Boolean
cfs::com::Messenger::MessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// /tmp/ACE_TAO/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for cfs::com::Messenger::MessageDataReader.

cfs::com::Messenger::MessageDataReader_ptr
TAO::Objref_Traits<cfs::com::Messenger::MessageDataReader>::duplicate (
    cfs::com::Messenger::MessageDataReader_ptr p)
{
  return cfs::com::Messenger::MessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<cfs::com::Messenger::MessageDataReader>::release (
    cfs::com::Messenger::MessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

cfs::com::Messenger::MessageDataReader_ptr
TAO::Objref_Traits<cfs::com::Messenger::MessageDataReader>::nil (void)
{
  return cfs::com::Messenger::MessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<cfs::com::Messenger::MessageDataReader>::marshal (
    const cfs::com::Messenger::MessageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



cfs::com::Messenger::MessageDataReader::MessageDataReader (void)
{}

cfs::com::Messenger::MessageDataReader::~MessageDataReader (void)
{
}

cfs::com::Messenger::MessageDataReader_ptr
cfs::com::Messenger::MessageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

cfs::com::Messenger::MessageDataReader_ptr
cfs::com::Messenger::MessageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

cfs::com::Messenger::MessageDataReader_ptr
cfs::com::Messenger::MessageDataReader::_nil (void)
{
  return 0;
}

cfs::com::Messenger::MessageDataReader_ptr
cfs::com::Messenger::MessageDataReader::_duplicate (MessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
cfs::com::Messenger::MessageDataReader::_tao_release (MessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
cfs::com::Messenger::MessageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:cfs/com/Messenger/MessageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* cfs::com::Messenger::MessageDataReader::_interface_repository_id (void) const
{
  return "IDL:cfs/com/Messenger/MessageDataReader:1.0";
}

::CORBA::Boolean
cfs::com::Messenger::MessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

